name: Build Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: UltimateSurvivalDefense
          path: |
            target/*.jar
            !target/*-sources.jar
            !target/*-javadoc.jar
